# Generated by Django 3.2.4 on 2023-09-14 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidence_log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidence',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='incidence',
            name='assigned_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
