# Generated by Django 3.2.4 on 2023-10-01 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidence_log', '0002_auto_20230914_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolution',
            name='created_by',
        ),
        migrations.AddField(
            model_name='incidence',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidence_added_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resolution',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_added_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='resolution',
            name='resolved_by',
        ),
        migrations.AddField(
            model_name='resolution',
            name='resolved_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
