# Generated by Django 3.2.4 on 2023-10-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0037_alter_kbviews_created'),
        ('incidence_log', '0003_auto_20231001_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='related_kb',
            field=models.ManyToManyField(to='knowledgebase.KnowledgeBase'),
        ),
    ]
