# Generated by Django 3.2.4 on 2023-10-08 11:09

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledgebase', '0037_alter_kbviews_created'),
        ('incidence_log', '0004_incidence_related_kb'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidence',
            name='resolution',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='(Any one from Related KB and Resolution is mandatory)', null=True),
        ),
        migrations.AddField(
            model_name='incidence',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidence',
            name='resolved_by',
            field=models.ManyToManyField(related_name='incidence_resolved_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='assigned_to',
            field=models.ManyToManyField(related_name='incidence_assigned_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='incidence_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='(Any one from Related KB and Incidence Description is mandatory)', null=True),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='related_kb',
            field=models.ManyToManyField(help_text='(Any one from Related KB and Incidence Description is mandatory)', to='knowledgebase.KnowledgeBase'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='urgency',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
        migrations.DeleteModel(
            name='Resolution',
        ),
    ]
