# Generated by Django 3.2.4 on 2023-10-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidence_log', '0005_auto_20231008_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidence',
            name='incidence_description',
        ),
        migrations.RemoveField(
            model_name='incidence',
            name='resolution',
        ),
    ]
