# Generated by Django 3.2.4 on 2023-10-10 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledgebase', '0037_alter_kbviews_created'),
        ('incidence_log', '0006_auto_20231008_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='incidence_assigned_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='impact',
            field=models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='related_kb',
            field=models.ManyToManyField(help_text='(KB about Incidence and Resolution Description.)', to='knowledgebase.KnowledgeBase'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='resolved_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='incidence_resolved_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Triggered'), (2, 'Acknowledged'), (3, 'Resolved')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='urgency',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, null=True),
        ),
    ]
