# Generated by Django 3.2.4 on 2024-02-01 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0037_alter_kbviews_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidence_log', '0007_auto_20231010_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='incidence_assigned_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='related_kb',
            field=models.ManyToManyField(blank=True, help_text='(KB about Incidence and Resolution Description.)', to='knowledgebase.KnowledgeBase'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='resolved_by',
            field=models.ManyToManyField(blank=True, related_name='incidence_resolved_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Triggered'), (3, 'Resolved')], default=1, null=True),
        ),
    ]
