# Generated by Django 3.2.4 on 2024-02-01 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0022_alter_taskmanager_created_at'),
        ('incidence_log', '0008_auto_20240201_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidence_reported_by_user', to='taskmanager.taskmanager'),
        ),
    ]
