# Generated by Django 3.2.4 on 2024-02-06 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0023_alter_taskmanager_assigned_to'),
        ('incidence_log', '0009_incidence_related_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidence_reported_related_task', to='taskmanager.taskmanager'),
        ),
    ]
