# Generated by Django 3.2.4 on 2022-12-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenseinfo', '0002_alter_licenseinfo_effective_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseinfo',
            name='effective_quantity',
            field=models.IntegerField(verbose_name='Effective Quantity'),
        ),
    ]
