# Generated by Django 3.2.4 on 2022-12-08 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licenseinfo', '0004_licensetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseinfo',
            name='license_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licenseinfo.licensetype'),
        ),
    ]
