# Generated by Django 3.2.4 on 2022-12-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenseinfo', '0005_alter_licenseinfo_license_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseinfo',
            name='license_status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='License Status'),
        ),
    ]
