# Generated by Django 3.2.4 on 2023-07-27 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licenseinfo', '0006_licenseinfo_license_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowsLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250, verbose_name='User Name')),
                ('user_id', models.CharField(max_length=20, verbose_name='User ID')),
                ('hostname', models.CharField(max_length=20, verbose_name='Hostname')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('branch', models.CharField(max_length=250, verbose_name='Branch/Div.')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delete_status', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winlicense_createdby', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winlicense_deleted', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winlicense_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
