# Generated by Django 3.2.4 on 2023-07-27 08:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licenseinfo', '0007_windowslicense'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WindowsLicense',
            new_name='M365License',
        ),
    ]
