# Generated by Django 3.2.4 on 2022-01-27 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledgebase', '0014_alter_kbviews_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('task_status', models.IntegerField(default=1)),
                ('due_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('task_steps_commentary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('delete_status', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tm_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tm_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskmanager_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskmanager_deleted_by_user', to=settings.AUTH_USER_MODEL)),
                ('reference_task', models.ManyToManyField(related_name='reftask', to='taskmanager.TaskManager')),
                ('subtask', models.ManyToManyField(related_name='tmsubtask', to='taskmanager.TaskManager')),
                ('task_procedure_or_kb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledgebase.knowledgebase')),
            ],
        ),
    ]
