# Generated by Django 3.2.4 on 2022-01-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='reference_task',
            field=models.ManyToManyField(blank=True, null=True, related_name='reftask', to='taskmanager.TaskManager'),
        ),
    ]
