# Generated by Django 3.2.4 on 2022-01-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_alter_taskmanager_reference_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmanager',
            name='reference_task',
        ),
        migrations.AddField(
            model_name='taskmanager',
            name='reference_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reftask', to='taskmanager.taskmanager'),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='subtask',
            field=models.ManyToManyField(blank=True, null=True, related_name='tmsubtask', to='taskmanager.TaskManager'),
        ),
    ]
