# Generated by Django 3.2.4 on 2022-01-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_auto_20220127_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
