# Generated by Django 3.2.4 on 2022-01-31 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0004_alter_taskmanager_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmanager',
            name='task_steps_commentary',
        ),
        migrations.CreateModel(
            name='TaskStepComentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('add_time', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasstepcomentary_created_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='taskmanager',
            name='task_steps_commentary',
            field=models.ManyToManyField(blank=True, null=True, related_name='tmcommentary', to='taskmanager.TaskStepComentary'),
        ),
    ]
