# Generated by Django 3.2.4 on 2022-02-02 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0005_auto_20220131_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmanager',
            name='subtask',
        ),
        migrations.AlterField(
            model_name='taskstepcomentary',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskstepcomentary_created_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
