# Generated by Django 3.2.4 on 2022-02-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0006_auto_20220202_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_status', models.CharField(blank=True, max_length=150, null=True)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('insert_date', models.DateTimeField(blank=True, null=True)),
                ('comment_add', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskmanager.taskstepcomentary')),
                ('ref_task_add', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_task_add', to='taskmanager.taskmanager')),
                ('sub_task_add', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_task_add', to='taskmanager.taskmanager')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.taskmanager')),
            ],
        ),
    ]
