# Generated by Django 3.2.4 on 2022-02-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0007_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='new_task_add',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
