# Generated by Django 3.2.4 on 2022-02-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0008_taskhistory_new_task_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='assigned_to_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='due_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
