# Generated by Django 3.2.4 on 2022-02-03 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0009_auto_20220203_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='ref_task_add',
        ),
    ]
