# Generated by Django 3.2.4 on 2022-02-03 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0010_remove_taskhistory_ref_task_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='ref_task_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_task_add', to='taskmanager.taskmanager'),
        ),
    ]
