# Generated by Django 3.2.4 on 2022-02-14 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0012_taskhistory_insert_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmanager',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='taskmanager',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='tm_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
