# Generated by Django 3.2.4 on 2022-02-14 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0013_auto_20220214_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='assigned_to_by',
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='th_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
