# Generated by Django 3.2.4 on 2022-02-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0031_alter_kbviews_created'),
        ('taskmanager', '0014_auto_20220214_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='task_procedure_or_kb',
            field=models.ManyToManyField(blank=True, null=True, to='knowledgebase.KnowledgeBase'),
        ),
        migrations.RemoveField(
            model_name='taskmanager',
            name='task_procedure_or_kb',
        ),
        migrations.AddField(
            model_name='taskmanager',
            name='task_procedure_or_kb',
            field=models.ManyToManyField(blank=True, null=True, to='knowledgebase.KnowledgeBase'),
        ),
    ]
