# Generated by Django 3.2.4 on 2022-02-14 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0015_auto_20220214_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='kb_insert_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_insert_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
