# Generated by Django 3.2.4 on 2022-03-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0016_taskhistory_kb_insert_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='task_visibility',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
