# Generated by Django 3.2.4 on 2022-03-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0017_taskmanager_task_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='task_visibility',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
