# Generated by Django 3.2.4 on 2023-01-01 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0037_alter_kbviews_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0018_taskhistory_task_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='assigned_to',
            field=models.ManyToManyField(related_name='th_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task_procedure_or_kb',
            field=models.ManyToManyField(to='knowledgebase.KnowledgeBase'),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='assigned_to',
            field=models.ManyToManyField(related_name='tm_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='task_procedure_or_kb',
            field=models.ManyToManyField(to='knowledgebase.KnowledgeBase'),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='task_steps_commentary',
            field=models.ManyToManyField(related_name='tmcommentary', to='taskmanager.TaskStepComentary'),
        ),
    ]
