# Generated by Django 3.2.4 on 2024-02-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0019_auto_20230101_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='task_from_ncidence',
            field=models.BooleanField(default=False),
        ),
    ]
