# Generated by Django 3.2.4 on 2024-02-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0020_taskmanager_task_from_ncidence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmanager',
            old_name='task_from_ncidence',
            new_name='task_from_incidence',
        ),
    ]
