# Generated by Django 3.2.4 on 2024-02-01 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0021_rename_task_from_ncidence_taskmanager_task_from_incidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
