# Generated by Django 3.2.4 on 2024-02-06 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0022_alter_taskmanager_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='tm_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
