# Generated by Django 3.2.4 on 2024-09-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0037_alter_kbviews_created'),
        ('taskmanager', '0024_auto_20240829_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='task_procedure_or_kb',
            field=models.ManyToManyField(blank=True, null=True, to='knowledgebase.KnowledgeBase'),
        ),
    ]
