# Generated by Django 3.2.4 on 2024-09-23 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0025_alter_taskmanager_task_procedure_or_kb'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
