# Generated by Django 3.2.4 on 2024-09-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0026_taskmanager_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='task_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tm_task_type', to='taskmanager.tasktype'),
        ),
    ]
