# Generated by Django 3.2.4 on 2021-09-15 10:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 15, 10, 24, 34, 829175, tzinfo=utc)),
        ),
    ]
