# Generated by Django 3.2.4 on 2021-09-15 10:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0020_alter_physicalserver_warranty_expiry_date'),
        ('knowledgebase', '0002_alter_postviews_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='KBViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPAddres', models.GenericIPAddressField(default='0.0.0.0')),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 9, 15, 10, 47, 42, 428773, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='related_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serverinfo.runningservices'),
        ),
        migrations.DeleteModel(
            name='PostViews',
        ),
        migrations.AddField(
            model_name='kbviews',
            name='kb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.knowledgebase'),
        ),
    ]
