# Generated by Django 3.2.4 on 2021-09-16 03:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0021_alter_physicalserver_warranty_expiry_date'),
        ('knowledgebase', '0003_auto_20210915_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbviews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 3, 11, 8, 690832, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='related_service',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='related_service',
            field=models.ManyToManyField(blank=True, null=True, to='serverinfo.RunningServices'),
        ),
    ]
