# Generated by Django 3.2.4 on 2021-09-16 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('knowledgebase', '0004_auto_20210916_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='kbviews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 9, 28, 32, 827498, tzinfo=utc)),
        ),
    ]
