# Generated by Django 3.2.4 on 2021-09-16 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0005_auto_20210916_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbviews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 17, 7, 31, 329961, tzinfo=utc)),
        ),
    ]
