# Generated by Django 3.2.4 on 2021-09-19 03:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledgebase', '0006_alter_kbviews_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbviews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 3, 14, 36, 197785, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledgebase_deleted_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
