# Generated by Django 3.2.4 on 2021-09-20 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0007_auto_20210919_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbviews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 8, 23, 9, 992132, tzinfo=utc)),
        ),
    ]
