# Generated by Django 3.2.4 on 2021-09-21 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0009_alter_kbviews_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbviews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 3, 18, 4, 723695, tzinfo=utc)),
        ),
    ]
