# Generated by Django 3.2.4 on 2021-09-21 04:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0010_alter_kbviews_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbviews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 4, 9, 47, 305048, tzinfo=utc)),
        ),
    ]
