# Generated by Django 3.2.4 on 2021-09-21 09:09

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledgebase', '0011_alter_kbviews_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='shared_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_with', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kbviews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 9, 9, 41, 212368, tzinfo=utc)),
        ),
    ]
