# Generated by Django 3.2.4 on 2021-09-26 04:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serverinfo', '0030_alter_physicalserver_warranty_expiry_date'),
        ('knowledgebase', '0012_auto_20210921_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbtopic',
            name='delete_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kbtopic',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kbtopic',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kbtopic_deleted_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kbviews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 26, 4, 50, 29, 48020, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='related_service',
            field=models.ManyToManyField(blank=True, to='serverinfo.RunningServices'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_with', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('protected', 'Protected')], default='draft', max_length=10),
        ),
    ]
