# Generated by Django 3.2.4 on 2022-01-27 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0015_alter_kbviews_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbviews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 11, 2, 46, 122845, tzinfo=utc)),
        ),
    ]
