# Generated by Django 3.2.4 on 2022-02-14 06:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0028_alter_kbviews_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbviews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 6, 19, 29, 199670, tzinfo=utc)),
        ),
    ]
