# Generated by Django 3.2.4 on 2022-03-15 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0032_alter_kbviews_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbviews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 19, 5, 5, 422849, tzinfo=utc)),
        ),
    ]
