# Generated by Django 3.2.4 on 2021-09-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='father_or_husband_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='NULL', max_length=150, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(default='NULL', max_length=150, verbose_name='Designation'),
        ),
    ]
