# Generated by Django 3.2.4 on 2022-03-24 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=250, verbose_name='Service Name')),
                ('mod_time', models.DateTimeField()),
                ('status_from', models.CharField(choices=[('auto', 'Auto'), ('Manual', 'Manual')], max_length=20)),
                ('server_ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('insertion_date', models.DateTimeField()),
                ('manually_inserted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manually_inserted_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
