# Generated by Django 3.2.4 on 2022-03-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0054_runningservices_service_log_loc'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serverinfo.runningservices'),
        ),
    ]
