# Generated by Django 3.2.4 on 2021-08-19 11:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serverinfo', '0002_auto_20210819_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='ostype',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ostype',
            name='deleted_by',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.RESTRICT, related_name='ostype_delete_user', to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='os_version',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='server_os_version', to='serverinfo.osversion'),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 18, 17, 44, 40, 608231), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
