# Generated by Django 3.2.4 on 2021-08-19 11:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serverinfo', '0003_auto_20210819_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='ostype',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='osversion',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osversion',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='osversion',
            name='deleted_by',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.RESTRICT, related_name='os_version_delete_user', to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='physicalserver',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='physicalserver',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='physicalserver',
            name='deleted_by',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.RESTRICT, related_name='pysical_server_delete_user', to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='project',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_by',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.RESTRICT, related_name='project_delete_user', to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='runningservices',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runningservices',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='runningservices',
            name='deleted_by',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.RESTRICT, related_name='running_service_delete_user', to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='deleted_by',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.RESTRICT, related_name='service_type_delete_user', to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='deleted_by',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.RESTRICT, related_name='virtual_server_delete_user', to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='vmlocationtype',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vmlocationtype',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='vmlocationtype',
            name='deleted_by',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.RESTRICT, related_name='vm_location_delete_user', to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='zone',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='zone',
            name='deleted_by',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.RESTRICT, related_name='zone_delete_user', to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='ostype',
            name='deleted_by',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.RESTRICT, related_name='os_type_delete_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='os_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='server_os_version', to='serverinfo.osversion'),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 18, 17, 57, 40, 98103), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
