# Generated by Django 3.2.4 on 2021-08-20 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0004_auto_20210819_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ostype',
            name='delete_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='delete_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 19, 12, 5, 28, 148835), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
