# Generated by Django 3.2.4 on 2021-08-20 06:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serverinfo', '0008_auto_20210820_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ostype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='os_type_delete_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='os_version_delete_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pysical_server_delete_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 19, 12, 57, 11, 641411), null=True, verbose_name='Warranty Expiry Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='project_delete_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='runningservices',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='running_service_delete_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='service_type_delete_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='virtualserver',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='virtual_server_delete_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vmlocationtype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vm_location_delete_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zone',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='zone_delete_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
