# Generated by Django 3.2.4 on 2021-08-22 04:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0009_auto_20210820_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalserver',
            name='form_factor',
        ),
        migrations.RemoveField(
            model_name='physicalserver',
            name='loc_in_rack',
        ),
        migrations.RemoveField(
            model_name='physicalserver',
            name='rack',
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='os_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='physical_server', to='serverinfo.ostype'),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='os_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='physical_server', to='serverinfo.osversion'),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 21, 10, 27, 0, 330021), null=True, verbose_name='Warranty Expiry Date'),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='physical_server', to='serverinfo.zone'),
        ),
        migrations.CreateModel(
            name='ServerRackInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack', models.IntegerField(verbose_name='Rack No.')),
                ('loc_in_rack', models.IntegerField(verbose_name='Server Location in Rack.')),
                ('form_factor', models.CharField(choices=[('1', '1U'), ('2', '2U'), ('4', '4U')], max_length=5, verbose_name='Form Factor')),
                ('server', models.ForeignKey(blank='False', null='False', on_delete=django.db.models.deletion.RESTRICT, related_name='server_rack_info', to='serverinfo.physicalserver')),
            ],
        ),
    ]
