# Generated by Django 3.2.4 on 2021-08-22 09:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0010_auto_20210822_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='service_name',
            field=models.ManyToManyField(blank=True, null=True, related_name='physical_server', to='serverinfo.RunningServices'),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='physical_server', to='serverinfo.servicetype'),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 21, 15, 30, 21, 716159), null=True, verbose_name='Warranty Expiry Date'),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serverinfo.zone'),
        ),
    ]
