# Generated by Django 3.2.4 on 2021-08-22 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0011_auto_20210822_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='server_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Server Name'),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 21, 18, 10, 5, 345491), null=True, verbose_name='Warranty Expiry Date'),
        ),
        migrations.AlterField(
            model_name='serverrackinfo',
            name='server',
            field=models.ForeignKey(blank='False', null='False', on_delete=django.db.models.deletion.CASCADE, related_name='server_rack_info', to='serverinfo.physicalserver'),
        ),
    ]
