# Generated by Django 3.2.4 on 2021-08-23 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0012_auto_20210822_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalserver',
            name='server_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Server Type'),
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='server_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Server Type'),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 22, 9, 36, 55, 355706), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
