# Generated by Django 3.2.4 on 2021-08-23 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0013_auto_20210823_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 22, 16, 28, 55, 222805), null=True, verbose_name='Warranty Expiry Date'),
        ),
        migrations.AlterUniqueTogether(
            name='serverrackinfo',
            unique_together={('rack', 'loc_in_rack')},
        ),
    ]
