# Generated by Django 3.2.4 on 2021-08-24 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0014_auto_20210823_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 23, 10, 56, 54, 67565), null=True, verbose_name='Warranty Expiry Date'),
        ),
        migrations.AlterField(
            model_name='serverrackinfo',
            name='form_factor',
            field=models.IntegerField(choices=[('1', '1U'), ('2', '2U'), ('4', '4U')], verbose_name='Form Factor'),
        ),
    ]
