# Generated by Django 3.2.4 on 2021-08-24 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0015_auto_20210824_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrackinfo',
            name='server_run_status',
            field=models.CharField(choices=[('On', 'On'), ('Off', 'Off'), ('Faulty', 'Faulty')], default='On', max_length=250, verbose_name='Server Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 23, 12, 56, 56, 571054), null=True, verbose_name='Warranty Expiry Date'),
        ),
        migrations.AlterField(
            model_name='serverrackinfo',
            name='form_factor',
            field=models.IntegerField(choices=[(1, '1U'), (2, '2U'), (4, '4U')], verbose_name='Form Factor'),
        ),
    ]
