# Generated by Django 3.2.4 on 2021-09-15 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0016_auto_20210824_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 14, 15, 9, 15, 607426), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
