# Generated by Django 3.2.4 on 2021-09-20 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0024_alter_physicalserver_warranty_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningservices',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='serverinfo.servicetype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 19, 14, 23, 9, 868572), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
