# Generated by Django 3.2.4 on 2021-09-20 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0025_auto_20210920_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalserver',
            name='service_type',
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 19, 18, 56, 53, 689770), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
