# Generated by Django 3.2.4 on 2021-09-21 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0026_auto_20210920_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualserver',
            name='service_type',
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 20, 9, 18, 4, 654272), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
