# Generated by Django 3.2.4 on 2021-09-21 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0027_auto_20210921_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 20, 10, 9, 47, 206265), null=True, verbose_name='Warranty Expiry Date'),
        ),
        migrations.AlterField(
            model_name='virtualserver',
            name='service_name',
            field=models.ManyToManyField(related_name='vm_runs_server', to='serverinfo.RunningServices'),
        ),
    ]
