# Generated by Django 3.2.4 on 2021-09-21 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0028_auto_20210921_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 20, 15, 9, 41, 132308), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
