# Generated by Django 3.2.4 on 2021-09-26 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0029_alter_physicalserver_warranty_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 25, 10, 50, 28, 965666), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
