# Generated by Django 3.2.4 on 2022-01-27 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0033_alter_physicalserver_warranty_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 1, 26, 17, 23, 41, 62274), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
