# Generated by Django 3.2.4 on 2022-01-27 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0034_alter_physicalserver_warranty_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 1, 26, 18, 34, 55, 320618), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
