# Generated by Django 3.2.4 on 2022-01-31 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0035_alter_physicalserver_warranty_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 1, 30, 8, 53, 48, 450500), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
