# Generated by Django 3.2.4 on 2022-02-03 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0039_alter_physicalserver_warranty_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 2, 8, 52, 30, 31033), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
