# Generated by Django 3.2.4 on 2022-02-03 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0044_alter_physicalserver_warranty_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 2, 17, 39, 40, 270066), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
