# Generated by Django 3.2.4 on 2022-02-14 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0046_alter_physicalserver_warranty_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 13, 13, 39, 41, 723389), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
