# Generated by Django 3.2.4 on 2022-03-15 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0049_alter_physicalserver_warranty_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 15, 1, 5, 5, 324962), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
