# Generated by Django 3.2.4 on 2022-03-17 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0051_alter_physicalserver_warranty_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 16, 10, 11, 29, 636802), null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
