# Generated by Django 3.2.4 on 2022-03-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0052_alter_physicalserver_warranty_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='server_receive_date',
            field=models.DateField(blank=True, null=True, verbose_name='Server Receive Date'),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Warranty Expiry Date'),
        ),
    ]
