# Generated by Django 3.2.4 on 2022-03-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0053_auto_20220317_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningservices',
            name='service_log_loc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Service Log Location'),
        ),
    ]
