# Generated by Django 3.2.4 on 2022-03-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0054_runningservices_service_log_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningservices',
            name='monitoring_enabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
