# Generated by Django 3.2.4 on 2022-03-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0055_runningservices_monitoring_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningservices',
            name='monitoring_enabled',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), ('1', 'Yes')], default=0, max_length=10, null=True, verbose_name='Enable Monitoring'),
        ),
    ]
