# Generated by Django 3.2.4 on 2022-10-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0056_alter_runningservices_monitoring_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningservices',
            name='monitoring_enabled',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], default=0, max_length=10, null=True, verbose_name='Enable Monitoring'),
        ),
        migrations.AlterField(
            model_name='serverrackinfo',
            name='form_factor',
            field=models.IntegerField(choices=[(1, '1U'), (2, '2U'), (3, '3U'), (4, '4U'), (5, '5U')], verbose_name='Form Factor'),
        ),
    ]
