# Generated by Django 3.2.4 on 2022-10-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0057_auto_20221010_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalserver',
            name='location',
        ),
        migrations.AddField(
            model_name='serverrackinfo',
            name='location',
            field=models.CharField(choices=[('dc', 'DC'), ('dr', 'DR')], default='dc', max_length=10, verbose_name='Server Location'),
        ),
    ]
