# Generated by Django 3.2.4 on 2022-10-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0058_auto_20221011_1048'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serverrackinfo',
            unique_together={('location', 'rack', 'loc_in_rack')},
        ),
    ]
