# Generated by Django 3.2.4 on 2022-11-23 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serverinfo', '0059_alter_serverrackinfo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_group_name', models.CharField(max_length=250, verbose_name='Service Group')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete_status', models.BooleanField(default=False)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='service_group_delete_user', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='runningservices',
            name='service_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='serverinfo.servicegroup'),
        ),
    ]
