# Generated by Django 3.2.4 on 2022-11-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0060_auto_20221123_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningservices',
            name='monitoring_enabled',
        ),
        migrations.RemoveField(
            model_name='runningservices',
            name='service_log_loc',
        ),
    ]
