# Generated by Django 3.2.4 on 2022-12-07 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serverinfo', '0062_licenseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenseinfo_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='licenseinfo',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenseinfo_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='licenseinfo',
            name='update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenseinfo_updatedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
