# Generated by Django 3.2.4 on 2022-12-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0063_auto_20221207_1301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LicenseInfo',
        ),
    ]
