# Generated by Django 3.2.4 on 2023-01-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0064_delete_licenseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='service_name',
            field=models.ManyToManyField(related_name='physical_server', to='serverinfo.RunningServices'),
        ),
        migrations.AlterField(
            model_name='runningservices',
            name='service_owner',
            field=models.CharField(choices=[('System', 'System'), ('Network', 'Network'), ('Security', 'Security'), ('DBA', 'DBA'), ('SDD', 'SDD'), ('Card', 'Card'), ('IPT', 'IPT'), ('BACH', 'BACH'), ('Others', 'Others')], max_length=250, verbose_name='Service Owner'),
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='service_group_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Service Group'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='service_type_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='virtualserver',
            name='service_name',
            field=models.ManyToManyField(blank=True, null=True, related_name='vm_runs_server', to='serverinfo.RunningServices'),
        ),
    ]
