# Generated by Django 3.2.4 on 2023-01-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0065_auto_20230101_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='service_name',
            field=models.ManyToManyField(blank=True, null=True, related_name='physical_server', to='serverinfo.RunningServices'),
        ),
    ]
