# Generated by Django 3.2.4 on 2022-10-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passwd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_server_name', models.CharField(max_length=250, verbose_name='Site or Servar Name')),
                ('ip_or_url', models.TextField(verbose_name='IP or URL')),
                ('username', models.TextField(verbose_name='Username')),
                ('password', models.TextField(verbose_name='Password')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
            ],
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterkey_hash', models.TextField(verbose_name='Master Password')),
                ('device_secret', models.TextField(max_length=150)),
            ],
        ),
    ]
