# Generated by Django 3.2.4 on 2022-10-10 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pass_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='master_key_name',
            field=models.CharField(default='My Mater Key', max_length=250, verbose_name='Master Key Name'),
        ),
        migrations.AddField(
            model_name='secret',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='secret',
            unique_together={('master_key_name', 'user_id')},
        ),
    ]
