# Generated by Django 3.2.4 on 2022-10-11 02:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pass_manager', '0002_auto_20221010_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwd',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='passwd',
            name='master_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pass_manager.secret'),
        ),
        migrations.AddField(
            model_name='secret',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
