# Generated by Django 3.2.4 on 2022-10-11 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pass_manager', '0003_auto_20221011_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='add_time',
        ),
        migrations.AddField(
            model_name='secret',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 11, 12, 27, 3, 69494, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secret',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
