# Generated by Django 3.2.4 on 2022-11-23 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pass_manager', '0006_auto_20221012_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwd',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
