# Generated by Django 3.2.4 on 2022-11-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_manager', '0007_alter_passwd_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secqlist',
            name='security_question',
            field=models.CharField(max_length=250, verbose_name='Enter Security Question'),
        ),
    ]
